id = "hledger"
name = "hledger"
description = "hledger/ledger plain-text accounting support."
version = "0.0.1"
schema_version = 1
authors = ["Chris Lloyd"]
repository = "https://github.com/chrislloyd/zed-hledger"
languages = ["languages/hledger"]

[grammars.hledger]
repository = "https://github.com/chrislloyd/tree-sitter-hledger"
rev = "8ee65478cb941a8cdaa798ffa73bb4437d4c4d07"
path = "journal"
